In [1]:
import tensorflow as tf
import numpy as np

/home/kerex/venv/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
inputs = np.load("../RNN_data/input.npy")
outputs = np.load("../RNN_data/output.npy")

In [3]:
n1553=inputs[np.where(inputs[:,0]==1553)[0]]

In [4]:
n1553.shape

(1973, 8)

In [5]:
final_input = []
y_ = []

#rnum=np.random.randint(inputs.shape[0]-8)
for i in range(10):
    rnum = i*20
    temp = inputs[rnum:rnum+10,2:6]
    final_input.append(temp)
    y_.append(inputs[rnum+10:rnum+20,2:6])
final_input = np.array(final_input)
y_ = np.array(y_)

In [6]:
print(final_input.shape)
print(y_.shape)
final_input
y_

(10, 10, 4)
(10, 10, 4)


array([[[35200, 35300, 34500, 34900],
        [34900, 35700, 34700, 35500],
        [35450, 35800, 34900, 35350],
        [35000, 35450, 34250, 34700],
        [34200, 35650, 34000, 35650],
        [35500, 36700, 35100, 36450],
        [36450, 36550, 35950, 36550],
        [36500, 36900, 36000, 36400],
        [36200, 36400, 35300, 36250],
        [36200, 36600, 35650, 35750]],

       [[33000, 34350, 32900, 34300],
        [33900, 34450, 33850, 34100],
        [34100, 34350, 33300, 33550],
        [33500, 33900, 32900, 33800],
        [34300, 35200, 34100, 35200],
        [35150, 35450, 34600, 35250],
        [35200, 35200, 34600, 34750],
        [34800, 35150, 33600, 34800],
        [34350, 34750, 34000, 34750],
        [35500, 35500, 34650, 35400]],

       [[35050, 35700, 35050, 35500],
        [35100, 35750, 34950, 35750],
        [35400, 35750, 35150, 35550],
        [35800, 35800, 34600, 35200],
        [35200, 35300, 34300, 34300],
        [34600, 34850, 34250, 34750],
        

In [7]:
inputs[300:310,2:6]

array([[31100, 32350, 31050, 31900],
       [31900, 32800, 31900, 32800],
       [33200, 33650, 33100, 33500],
       [34850, 35500, 34350, 34850],
       [35000, 35500, 34550, 34900],
       [35200, 36450, 34950, 36450],
       [37750, 37800, 36850, 36850],
       [36850, 37500, 36600, 37400],
       [37900, 38350, 36800, 36950],
       [36550, 37500, 36550, 37200]])

In [8]:
del outputs, states

NameError: name 'states' is not defined

In [17]:
n_inputs = 4
n_outputs = 4
n_neurons = 200
n_time_steps = 10

tf.reset_default_graph()

X = tf.placeholder(tf.float32, [None, n_time_steps, n_inputs])
y = tf.placeholder(tf.float32, [None, n_time_steps, n_outputs])
basic_cell = tf.contrib.rnn.OutputProjectionWrapper(
    tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu), output_size=n_outputs)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

In [52]:
learning_rate = 0.01
loss = tf.reduce_mean(tf.square(outputs - y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
train_op = optimizer.minimize(loss)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    for _ in range(100):
        sess.run(train_op, feed_dict={X:final_input, y:y_})
        
    print(loss.eval(feed_dict={X: final_input, y:y_}))
    y_pred = sess.run(outputs, feed_dict={X: inputs[300:310,2:6].reshape(-1,10,4)})

5120028.0


In [53]:
inputs[300:310,2:6]

array([[31100, 32350, 31050, 31900],
       [31900, 32800, 31900, 32800],
       [33200, 33650, 33100, 33500],
       [34850, 35500, 34350, 34850],
       [35000, 35500, 34550, 34900],
       [35200, 36450, 34950, 36450],
       [37750, 37800, 36850, 36850],
       [36850, 37500, 36600, 37400],
       [37900, 38350, 36800, 36950],
       [36550, 37500, 36550, 37200]])

In [55]:
y_pred

array([[[31554.379, 32376.918, 31372.92 , 32129.436],
        [32693.111, 33067.617, 32272.41 , 32819.082],
        [33723.227, 33994.234, 33109.45 , 33652.203],
        [34959.84 , 35823.344, 34468.234, 35126.184],
        [35735.65 , 36117.043, 35154.02 , 35700.645],
        [36365.973, 36887.1  , 35869.33 , 36429.934],
        [37723.836, 38404.113, 37048.81 , 37906.78 ],
        [37838.715, 38327.12 , 37280.58 , 37826.668],
        [38226.516, 38865.105, 37622.406, 38348.09 ],
        [37839.535, 38275.52 , 37281.055, 37771.277]]], dtype=float32)

In [56]:
inputs[310:320,2:6]

array([[37050, 37900, 37050, 37850],
       [37800, 37950, 37250, 37900],
       [38300, 38400, 37300, 37500],
       [37150, 38050, 37150, 37650],
       [37650, 38400, 37600, 38000],
       [38400, 38400, 37550, 38050],
       [37800, 39000, 37700, 38900],
       [38900, 38900, 38100, 38600],
       [38350, 38350, 36800, 37650],
       [37200, 37650, 35600, 36550]])